ENT.Type = "anim"
ENT.Base = "test_base"
 
ENT.PrintName		= "Basic Power Plant"
ENT.Author			= "[RG]Uggleking [RG]nickelpro"
ENT.Contact			= "Don't"
ENT.Purpose			= "Make it rain baby"
ENT.Instructions	= "Use with care. Always handle with gloves."
ENT.Category 		= "Power Plants"
ENT.PowerSlots		= 5
ENT.PowerUsage 		= 0
ENT.Price 			= 1000
ENT.PowerDist       = 1024
ENT.Delay 			= 60
ENT.UseCost 		= 5
ENT.Player 			= nil
ENT.Spawnable 		= true
ENT.Basewars 		= true
ENT.MaxHealth 		= 100
ENT.Fliped 			= false
ENT.Model 			= "models/props_c17/furnitureStove001a.mdl"