ENT.Type = "anim"
ENT.Base = "test_base"
 
ENT.PrintName		= "Bronze Printer"
ENT.Author			= "[RG]Uggleking"
ENT.Contact			= "Don't"
ENT.Purpose			= "Make it rain baby"
ENT.Instructions	= "Use with care. Always handle with gloves."
ENT.Category 		= "Printers"
ENT.Delay 			= 18
ENT.PayLow			= 82
ENT.PayHigh 		= 110
ENT.PowerUsage		= 1
ENT.Price 			= 3200
ENT.Spawnable 		= true
ENT.Basewars 		= true
ENT.MaxHealth 		= 200
ENT.Buyer 			= "WHYYY"
ENT.HealthRing		= {100,27,0} -- What the fuck this does is going to need some experimentation