ENT.Type = "anim"
ENT.Base = "base_gmodentity"
 
ENT.PrintName		= "Dispenser"
ENT.Author			= "[RG]Uggleking"
ENT.Contact			= "Don't"
ENT.Purpose			= "Make it rain baby"
ENT.Instructions	= "Use with care. Always handle with gloves."
ENT.Price 			= "1500"
ENT.Model 			= "models/props_lab/reciever_cart.mdl"
ENT.Ent_Name 		= "dispenser"